services:
  - type: web
    name: drupal-tnb
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_VERSION
        value: 8.3
      - key: DATABASE_URL
        fromDatabase:
          name: drupal-db
          property: connectionString
      - key: TRUSTED_HOST_PATTERNS
        value: "^.*\\.onrender\\.com$"
      - key: HASH_SALT
        generateValue: true

databases:
  - name: drupal-db
    databaseName: drupal
    user: drupal
    plan: free
    postgresMajorVersion: "14"
    ipAllowList: [] 